"""
Birthday Quest - Session Service

Business logic for creating, recovering, reading, and completing
Birthday Quest sessions.

This service owns session lifecycle rules. Routes should call this
service instead of directly manipulating Firebase.
"""

from __future__ import annotations

from typing import Any

from models.session import Session
from services.firebase_service import (
    get_document_data,
    set_document_data,
    update_document_data,
)
from utils.ids import generate_session_id
from utils.logging import (
    get_logger,
    log_info,
    log_warning,
)
from utils.timestamps import utc_now_iso


logger = get_logger(__name__)

SESSIONS_COLLECTION = "sessions"

INITIAL_SESSION_STATE = "NEW"

COMPLETED_SESSION_STATE = "SESSION_COMPLETE"


def create_session(
    metadata: dict[str, Any] | None = None,
) -> Session:
    """
    Create and persist a new Birthday Quest session.

    The session ID and lifecycle timestamps are generated by the
    backend and cannot be supplied by the client.
    """
    if metadata is None:
        metadata = {}

    if not isinstance(metadata, dict):
        raise TypeError(
            "metadata must be a dictionary."
        )

    session_id = generate_session_id()
    now = utc_now_iso()

    session = Session(
        session_id=session_id,
        state=INITIAL_SESSION_STATE,
        created_at=now,
        updated_at=now,
        last_activity_at=now,
        completed_at=None,
        version=1,
        active=True,
        metadata=dict(metadata),
    )

    set_document_data(
        SESSIONS_COLLECTION,
        session.session_id,
        session.to_dict(),
    )

    log_info(
        logger,
        "session_created",
        session_id=session.session_id,
        state=session.state,
    )

    return session


def get_session(
    session_id: str,
) -> Session | None:
    """
    Retrieve a session by ID.

    Returns None when the session does not exist.
    """
    data = get_document_data(
        SESSIONS_COLLECTION,
        session_id,
    )

    if data is None:
        return None

    return Session.from_dict(data)


def recover_session(
    session_id: str,
) -> Session | None:
    """
    Recover an existing active session.

    Recovery updates activity timestamps but does not alter the
    quest state.
    """
    session = get_session(session_id)

    if session is None:
        log_warning(
            logger,
            "session_not_found",
            session_id=session_id,
        )
        return None

    if not session.active:
        log_warning(
            logger,
            "inactive_session_recovery_attempt",
            session_id=session.session_id,
            state=session.state,
        )
        return None

    if session.state == COMPLETED_SESSION_STATE:
        log_warning(
            logger,
            "completed_session_recovery_attempt",
            session_id=session.session_id,
        )
        return None

    now = utc_now_iso()
    next_version = session.version + 1

    update_document_data(
        SESSIONS_COLLECTION,
        session.session_id,
        {
            "updated_at": now,
            "last_activity_at": now,
            "version": next_version,
        },
    )

    session.updated_at = now
    session.last_activity_at = now
    session.version = next_version

    log_info(
        logger,
        "session_recovered",
        session_id=session.session_id,
        state=session.state,
        version=session.version,
    )

    return session


def update_session_activity(
    session: Session,
) -> Session:
    """
    Update the activity timestamp for an active session.

    The quest state is deliberately not changed here.
    """
    if not isinstance(session, Session):
        raise TypeError(
            "session must be a Session instance."
        )

    if not session.active:
        raise ValueError(
            "Cannot update activity for an inactive session."
        )

    if session.state == COMPLETED_SESSION_STATE:
        raise ValueError(
            "Cannot update activity for a completed session."
        )

    now = utc_now_iso()
    next_version = session.version + 1

    update_document_data(
        SESSIONS_COLLECTION,
        session.session_id,
        {
            "updated_at": now,
            "last_activity_at": now,
            "version": next_version,
        },
    )

    session.updated_at = now
    session.last_activity_at = now
    session.version = next_version

    return session


def update_session_state(
    session: Session,
    new_state: str,
) -> Session:
    """
    Persist a session state change.

    This function intentionally performs only persistence-level
    validation. Legal quest transitions will be controlled by the
    quest service/state machine.
    """
    if not isinstance(session, Session):
        raise TypeError(
            "session must be a Session instance."
        )

    if not isinstance(new_state, str):
        raise TypeError(
            "new_state must be a string."
        )

    new_state = new_state.strip()

    if not new_state:
        raise ValueError(
            "new_state cannot be empty."
        )

    if not session.active:
        raise ValueError(
            "Cannot update an inactive session."
        )

    if session.state == COMPLETED_SESSION_STATE:
        raise ValueError(
            "A completed session cannot change state."
        )

    now = utc_now_iso()
    next_version = session.version + 1

    update_document_data(
        SESSIONS_COLLECTION,
        session.session_id,
        {
            "state": new_state,
            "updated_at": now,
            "last_activity_at": now,
            "version": next_version,
        },
    )

    session.state = new_state
    session.updated_at = now
    session.last_activity_at = now
    session.version = next_version

    return session


def complete_session(
    session: Session,
) -> Session:
    """
    Mark an active session as permanently completed.
    """
    if not isinstance(session, Session):
        raise TypeError(
            "session must be a Session instance."
        )

    if not session.active:
        raise ValueError(
            "Session is already inactive."
        )

    if session.state == COMPLETED_SESSION_STATE:
        return session

    now = utc_now_iso()
    next_version = session.version + 1

    update_document_data(
        SESSIONS_COLLECTION,
        session.session_id,
        {
            "state": COMPLETED_SESSION_STATE,
            "active": False,
            "completed_at": now,
            "updated_at": now,
            "last_activity_at": now,
            "version": next_version,
        },
    )

    session.state = COMPLETED_SESSION_STATE
    session.active = False
    session.completed_at = now
    session.updated_at = now
    session.last_activity_at = now
    session.version = next_version

    log_info(
        logger,
        "session_completed",
        session_id=session.session_id,
    )

    return session
